# Generated by Django 3.0.1 on 2019-12-18 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Empresa', models.CharField(max_length=80)),
                ('cnpj_Empresa', models.CharField(blank=True, max_length=18, null=True)),
                ('processoRaiz', models.CharField(max_length=20)),
                ('contrato', models.CharField(blank=True, max_length=9, null=True)),
                ('objeto', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_contratual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_utilizado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dataAssinatura', models.DateField(verbose_name='data de assinatura')),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('siape', models.CharField(blank=True, max_length=7, null=True)),
                ('portaria', models.CharField(blank=True, max_length=10, null=True)),
                ('setor', models.CharField(blank=True, max_length=7, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do Fiscal')),
                ('ramal', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza_despesa', models.CharField(max_length=6)),
                ('subelemento', models.CharField(max_length=2)),
                ('descricao', models.CharField(max_length=70)),
                ('saldo_empenhado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GestaoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processoSei', models.CharField(max_length=20)),
                ('numNota', models.CharField(max_length=20)),
                ('mesCompetencia', models.CharField(max_length=8)),
                ('emissNota', models.DateField(verbose_name='data de emissão da nota')),
                ('recebido_nota', models.DateField(verbose_name='data de recebimento')),
                ('atesteNota', models.DateField(verbose_name='data de ateste')),
                ('totalNota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('glosaMaterial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('glosaServico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obs', models.TextField(verbose_name='Observações')),
                ('contratada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.Empresa', verbose_name='Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.Fiscal', verbose_name='Fiscal'),
        ),
    ]
