# Generated by Django 3.0.1 on 2019-12-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='processoRaiz',
            field=models.CharField(max_length=20, verbose_name='Processo Raiz'),
        ),
    ]
