# Generated by Django 3.0.1 on 2019-12-19 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20191218_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='fiscal',
        ),
        migrations.AddField(
            model_name='empresa',
            name='Nomfiscal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Fiscal', to='gestao.Fiscal'),
            preserve_default=False,
        ),
    ]
