# Generated by Django 3.0.1 on 2019-12-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_auto_20191218_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nome_Empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa',
            field=models.CharField(default=1, max_length=80, verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
