# Generated by Django 3.0.1 on 2019-12-19 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_auto_20191218_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='Nomfiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fiscal', to='gestao.Fiscal', verbose_name='Fiscal'),
        ),
    ]
