# Generated by Django 3.0.1 on 2019-12-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_auto_20191219_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestaocontrato',
            old_name='Empresa',
            new_name='empresa',
        ),
    ]
