# Generated by Django 3.0.1 on 2019-12-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_auto_20191219_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestaocontrato',
            old_name='glosaMaterial',
            new_name='totalPago',
        ),
        migrations.RemoveField(
            model_name='gestaocontrato',
            name='glosaServico',
        ),
    ]
