# Generated by Django 3.0.1 on 2019-12-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_auto_20191221_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='funcao',
            field=models.TextField(default=1, verbose_name='Função da despesa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(max_length=6, verbose_name='Código da despesa'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='natureza',
            field=models.CharField(max_length=50, verbose_name='Descrição da despesa'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor orçamentário'),
        ),
    ]
