# Generated by Django 3.0.1 on 2019-12-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_auto_20191221_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubrica',
            old_name='valorDisponRubrica_empenhado',
            new_name='valorDisponRubrica',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo',
            field=models.CharField(default=1, max_length=20, verbose_name='Descrição da despesa'),
            preserve_default=False,
        ),
    ]
