# Generated by Django 3.0.1 on 2019-12-21 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_auto_20191221_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrica',
            name='natureza_despesa',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='obsReserva',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='saldo_reservado',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='valorDisponRubrica',
        ),
        migrations.AddField(
            model_name='rubrica',
            name='codigoDesp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestao.Orcamento', verbose_name='Código da despesa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='tipo',
            field=models.CharField(max_length=20, verbose_name='Tipo'),
        ),
    ]
